## Tensor basics

### Creating Tensors

In [21]:
import torch

# From list
t1 = torch.tensor([1, 2, 3])

# Zeros / Ones
t2 = torch.zeros(3, 3)
t3 = torch.ones(2, 2)

# Random
t4 = torch.rand(2, 3)

# Range
t5 = torch.arange(0, 10)

print(t1, t2, t3, t4, t5)

tensor([1, 2, 3]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1.],
        [1., 1.]]) tensor([[0.6015, 0.8030, 0.0989],
        [0.6184, 0.1557, 0.0824]]) tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Tensor Shape

In [22]:
t = torch.rand(3, 4)
print(t.shape)   # (3, 4)
print(t.size())  # same as shape

torch.Size([3, 4])
torch.Size([3, 4])


### Tensor Data Types

In [23]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)

print(t.dtype)

torch.float32


### Math Scalar Operations

In [24]:
t = torch.tensor([1, 2, 3])

print(t + 5)
print(t * 2)
print(t / 2)

tensor([6, 7, 8])
tensor([2, 4, 6])
tensor([0.5000, 1.0000, 1.5000])


### Element-wise Operations

In [25]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


### Reduction Operations

In [26]:
t = torch.tensor([1.0, 2.0, 3.0])

print(torch.sum(t))
print(torch.mean(t))
print(torch.max(t))

tensor(6.)
tensor(2.)
tensor(3.)


### Matrix Operations

In [27]:
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# Matrix multiplication
C = torch.matmul(A, B)

print(C)

tensor([[0.7668, 0.9551],
        [0.7707, 0.8727]])


### Comparison Operations

In [28]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

print(a > b)
print(a == b)

tensor([False, False,  True])
tensor([False,  True, False])


### Special Functions

In [29]:
t = torch.tensor([1.0, 4.0, 9.0])

print(torch.sqrt(t))
print(torch.exp(t))
print(torch.log(t))

tensor([1., 2., 3.])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([0.0000, 1.3863, 2.1972])


### In-place Operations

In [30]:
t = torch.tensor([1, 2, 3])

t.add_(5)   # inplace
print(t)

tensor([6, 7, 8])


### Copying a Tensor

In [31]:
a = torch.tensor([1, 2, 3])

b = a.clone()   # safe copy
b[0] = 100

print(a)  # unchanged
print(b)

tensor([1, 2, 3])
tensor([100,   2,   3])


## Backpropagation

**Formula:**

* Forward → compute output
* Loss → error
* Backward → gradients
* Update weights

### Weight Initialization

In [32]:
w = torch.randn(2, 2, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

### Forward Propagation

In [33]:
x = torch.tensor([[1.0, 2.0]])

y = x @ w + b   # linear layer

### Weight Update (Gradient Descent)

In [34]:
loss = y.sum()

loss.backward()

# Update
with torch.no_grad():
    w -= 0.01 * w.grad
    b -= 0.01 * b.grad

    w.grad.zero_()
    b.grad.zero_()

In [35]:
import torch

# Data
x = torch.tensor([[1.0, 2.0]])
y_true = torch.tensor([[1.0]])

# Weights
w = torch.randn(2, 1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Forward
y_pred = x @ w + b

# Loss
loss = (y_pred - y_true)**2

# Backward
loss.backward()

# Update
with torch.no_grad():
    w -= 0.01 * w.grad
    b -= 0.01 * b.grad

    w.grad.zero_()
    b.grad.zero_()

print("Updated weights:", w)

Updated weights: tensor([[-0.3242],
        [-1.1737]], requires_grad=True)
